parameters:
#    my_app_carnet.example.class: MyApp\CarnetBundle\Example

services:
#    my_app_carnet.example:
#        class: %my_app_carnet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
